spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/board
    password: dklinge00!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'false'
    hibernate:
      ddl-auto: update
  elasticsearch:
    uris: "http://localhost:9200"
